const products = [
    {id: 1, name: 'Horizon Forbidden West', plataforma: 'PS4 y PS5', unidades: 60, genero: 'Aventura', price: 69.99, image: "Images/Horizon Forbidden Wes.jpg" },
    {id: 2, name: 'Kena Bridge of Spirits', plataforma: 'PS4 y PS5', unidades: 60, genero: 'Aventura', price: 39.99, image: "Images/Kena Bridge of Spirits.jpg" },
    {id: 3, name: 'Assassins Creed Valhalla', plataforma: 'PS4', unidades: 60, genero: 'Aventura', price: 23.99,  image: "Images/Assassins Creed Valhalla.jpg" },
    {id: 4, name: 'The Last of Us Part II', plataforma: 'PS4', unidades: 60, genero: 'Aventura', price: 39.99, image: "Images/The Last of Us Part II.jpg"},
    {id: 5, name: 'Returnal', plataforma: 'PS5', unidades: 60, genero: 'Aventura', price: 69.99, image: "Images/Returnal.jpg"},
    {id: 6, name: 'Ghostwire: Tokyo', plataforma: 'PS5', unidades: 60, genero: 'Aventura', price: 59.99, image: "Images/Ghostwire Tokyo.jpg" },
    {id: 7, name: 'Trek to Yomi', plataforma: 'PS4 y PS5', unidades: 60, genero: 'Acción', price: 19.99, image: "Images/Trek to Yomi.jpg"},
    {id: 8, name: 'Sniper Elite 5', plataforma: 'PS4 y PS5', unidades: 60, genero: 'Acción', price: 59.99, image: "Images/Sniper Elite 5.jpg" },
    {id: 9, name: 'Far Cry 6', plataforma: 'PS4 y PS5', unidades: 60, genero: 'Acción', price: 39.99, image: "Images/Far Cry 6.jpg"},
    {id: 10, name: 'Grand Theft Auto', plataforma: 'PS4 y PS5', unidades: 60, genero: 'Acción', price: 29.99, image: "Images/Grand Theft Auto v.jpg"},
    {id: 11, name: 'God Of War', plataforma: 'PS4', unidades: 60, genero: 'Acción', price: 19.99, image: "Images/God Of War.jpg"},
    {id: 12, name: 'Watch Dogs: Legion', plataforma: 'PS4 y PS5', unidades: 60, genero: 'Acción', price: 15.99, image: "Images/Watch Dogs Legion.jpg"},
    {id: 13, name: 'NBA 2K22', plataforma: 'PS4 y PS5', unidades: 60, genero: 'Deportes', price: 69.99, image: "Images/NBA 2K22.jpg"},
    {id: 14, name: 'Madden NFL 22', plataforma: 'PS4 y PS5', unidades: 60, genero: 'Deportes', price: 99.99, image: "Images/Madden NFL 22.jpg"},
    {id: 15, name: 'FIFA 22', plataforma: 'PS4 y PS5', unidades: 60, genero: 'Deportes', price: 59.99, image: "Images/FIFA 22.jpg"},
    {id: 16, name: 'WWE 2K22', plataforma: 'PS4 yPS5', unidades: 60, genero: 'Deportes', price: 69.99, image: "Images/WWE 2K22.jpg"},
    {id: 17, name: 'F1 22', plataforma: 'PS4 y PS5', unidades: 60, genero: 'Deportes', price: 69.99, image: "Images/F1 22.jpg"},
    {id: 18, name: 'Matchpoint - Tennis', plataforma: 'PS4 y PS5', unidades: 60, genero: 'Deportes', price: 49.99, image: "Images/Matchpoint  Tennis.jpg"},
    {id: 19, name: 'Saints Row', plataforma: 'PS5', unidades: 60, genero: 'Juego de disparos', price: 30.99, image: "Images/Saints Row.jpg"},
    {id: 20, name: 'Cyberpunk', plataforma: 'PS4 y PS5', unidades: 60, genero: 'Juego de disparos', price: 49.99, image: "Images/Cyberpunk.jpg"},
    {id: 21, name: 'Apex Legends', plataforma: 'PS5', unidades: 60, genero: 'Juego de disparos', price: 0, image: "Images/Apex Legends.jpg"},
    {id: 22, name: 'Battlefield 2042', plataforma: 'PS4', unidades: 60, genero: 'Juego de disparos', price: 59.99, image: "Images/Battlefield 2042.jpg"},
    {id: 23, name: 'Fortnite', plataforma: 'PS4 y PS5', unidades: 60, genero: 'Juego de disparos', price: 0, image: "Images/Fortnite.jpg"},
    {id: 24, name: 'Red Dead Redemption 2', plataforma: 'PS5', unidades: 60, genero: 'Juego de disparos', price: 30.99, image: "Images/Red Dead Redemption 2.jpg"},
    {id: 25, name: 'Hello Neighbor 2', plataforma: 'PS4 y PS5', unidades: 60, genero: 'Terror', price: 39.99, image: "Images/Hello Neighbor 2.jpg"},
    {id: 26, name: 'The Quarry', plataforma: 'PS4 y PS5', unidades: 60, genero: 'Terror', price: 69.99, image: ""},
    {id: 27, name: 'The Trap Remake', plataforma: 'PS5', unidades: 60, genero: 'Terror', price: 29.99, image: "https://sm.ign.com/t/ign_es/game/r/resident-e/resident-evil-village_6xmb.1200.jpg"},
    {id: 28, name: 'Chernobylite', plataforma: 'PS5', unidades: 60, genero: 'Terror', price: 29.99, image: ""},
    {id: 29, name: 'Insomnis Long Night ', plataforma: 'PS4', unidades: 60, genero: 'Terror', price: 19.99, image: "https://image.api.playstation.com/cdn/EP0102/CUSA00804_00/i9ZEb8fUeOTGOhPgphchEPYpyW721BYz.png"},
    {id: 30, name: 'TAPE: Unveil the Memories', plataforma: 'PS4', unidades: 60, genero: 'Terror', price: 19.99, image: "https://image.api.playstation.com/cdn/UP2113/CUSA06623_00/5vXtP0O5fmnnyrNnWAinTz57d04szG3b.png"}
];